### PR TITLE
Update welcome.js

### PR DESCRIPTION
**Pull request by oohwooh**
Seperate the lines with all the channels, so that they come in one by one. Might be a little spammy though.

### CODE REVIEW

**Comment by tylermenezes** [comment]
Do you think this might be too annoying? That's why I didn't do it that way to begin with. (Alternatively maybe we could reduce the number of rooms we suggest)

**Comment by oohwooh** [comment]
Maybe we could recommend half of the channels we currently are, then the next day he could say "just checking in and making sure everything is okay, I thought of a few more channels you might like as well:" or something to that effect.

**Comment by tylermenezes** [comment]
That sounds like a cool idea. Do you want to make that change in this PR or have my close it and commit something similar directly?

**Comment by oohwooh** [comment]
I can do that in this PR.

**Pull request closed without merging**
